title: Welcome Golam Muktadir 
description: This is Golam Muktadir's  personal Web site and CV and Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "gmuktadir.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    MD.GOLAM MUKTADIR
author-image:   gm_profilepic.jpg
author-job:     Research Assistant, Web Application Developer 
author-email:   gm.cse.duet@gmail.com # Add your email for contant form.
author-twitter: go_muktadir # Add your twitter account
about-author:   Research Assistant | Web Application Developer | Data Science Enthusiast | Graduate in Computer Science And Engineering

# Social settings
social-twitter:   go_muktadir
social-facebook:  go_muktadir
social-github:    gmuktadir
social-pinterest: 
social-instagram: #g.muktadir
social-youtube:
social-vk:   
social-linkedin:  mgmuktadir

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
